import axios from "axios";
import Navbar from "components/Navbar/Navbar";
import { GetStaticPaths, GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import {
  MdFacebook,
  MdLocationPin,
  MdOutbond,
  MdOutlineCalendarMonth,
  MdPhone,
  MdWork,
} from "react-icons/md";
import { User } from "types.global";
import styles from "../../styles/user.module.scss";

interface UserProps {
  user: User;
}

const Index: React.FC<UserProps> = ({ user }) => {
  // console.log(user);
  const createAt = new Date(user?.createdAt);
  const date = Intl.DateTimeFormat("en-US", {
    month: "long",
    year: "numeric",
  }).format(createAt);

  return (
    <div className={styles.user_profile}>
      <Head>
        <title>{user?.fullname}</title>
        <meta name="description" content="Generated by sociatek" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <div className={styles.user_profile_main}>
        <div className={styles.user_profilee}>
          <Image
            src={user?.coverPhoto}
            alt="sociatek user cover"
            height={150}
            width={400}
            className={styles.user_cover}
          />
          <Image
            src={user?.profilePicture}
            alt="sociatek user profile"
            height={120}
            width={120}
            className={styles.user_dp}
          />

          <div className={styles.user_profile_detail}>
            <h2>
              {user?.fullname}
              <span> ({user?.username})</span>
            </h2>
            <p>{user?.about}</p>

            <div className={styles.user_activities}>
              <p className={styles.follow_sec}>
                <span>{user?.followers?.length}</span> Followers
              </p>
              <p className={styles.follow_sec}>
                <span>{user?.following?.length}</span> Following
              </p>
            </div>

            <div className={styles.user_profile_contact}>
              <p>
                <MdLocationPin className={styles.contact_icon} />{" "}
                {user?.location}
              </p>
              <p>
                <MdPhone className={styles.contact_icon} /> {user?.phone}
              </p>
              <p>
                <MdWork className={styles.contact_icon} /> {user?.profession}
              </p>
            </div>

            <div className={styles.contact_btm}>
              <div className={styles.contact_btmm}>
                <MdFacebook className={styles.contact_btm_icon} />
                Facebook:
                <div className={styles.contact_btm_fb}>
                  {user?.facebook ? (
                    <p style={{ cursor: "pointer" }}>
                      <Link
                        href={user?.facebook}
                        style={{ color: "rgba(0, 0, 0, 0.795)" }}
                        target="blank"
                      >
                        <MdOutbond
                          style={{
                            marginBottom: "-13px",
                            fontSize: "25px",
                            marginLeft: "4px",
                          }}
                        />
                      </Link>
                    </p>
                  ) : (
                    <p style={{ marginBottom: "4px", marginLeft: "4px" }}>
                      Not Signed!
                    </p>
                  )}
                </div>
              </div>

              <div className={styles.contact_btm_join}>
                <MdOutlineCalendarMonth className={styles.contact_btm_icon} />
                Joined: {date}
              </div>
            </div>
          </div>
        </div>

        <div className={styles.user_posts}>
          <h3>posts</h3>
          <h3>activities</h3>
        </div>
      </div>
    </div>
  );
};

export default Index;

// Fetch the list of user IDs from an API or database
export const getStaticPaths: GetStaticPaths = async () => {
  const res = await axios.get("http://localhost:4000/api/users/all");
  const users = await res.data.message;

  const paths = users.map((user: User) => ({
    params: {
      userid: user._id,
    },
  }));

  return {
    paths,
    fallback: false,
  };
};

//  Fetch the user data based on the ID from an API or database
export const getStaticProps: GetStaticProps<UserProps> = async (context) => {
  const { params } = context;
  const res = await axios.get(
    `http://localhost:4000/api/user/${params?.userid}`
  );
  const data = await res.data.message;

  return {
    props: {
      user: data,
    },
  };
};
