import axios from "axios";
import Navbar from "components/Navbar/Navbar";
import { GetStaticPaths, GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import { User } from "types.global";
import styles from "../../styles/profile.module.scss";

interface UserProps {
  user: User;
}

const Index: React.FC<UserProps> = ({ user }) => {
  // console.log(user);

  return (
    <div className={styles.user_profile}>
      <Head>
        <title>{user?.fullname}</title>
        <meta name="description" content="Generated by sociatek" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <div className={styles.user_profile_main}>
        <div className={styles.user_profile}>
          <Image
            src={user?.coverPhoto}
            alt="sociatek user cover"
            height={100}
            width={800}
            className={styles.user_cover}
          />
          <Image
            src={user?.profilePicture}
            alt="sociatek user profile"
            height={100}
            width={100}
            className={styles.user_dp}
          />

          <div className={styles.user_profile_detail}>
            <h2>
              {user?.fullname}
              <span> ({user?.username})</span>
            </h2>{" "}
            ()
            <p>{user?.about}</p>
            <div className={styles.user_profile_contact}>
              <p>{user?.location}</p>
              <p>{user?.phone}</p>
              <p>{user?.profession}</p>
            </div>
            <p>Facebook: {user.facebook ? user.facebook : "Not signed"}</p>
          </div>
        </div>

        <div className={styles.user_posts}>
          <h3>posts</h3>
          <h3>activities</h3>
        </div>
      </div>
    </div>
  );
};

export default Index;

// Fetch the list of user IDs from an API or database
export const getStaticPaths: GetStaticPaths = async () => {
  const res = await axios.get("http://localhost:4000/api/users/all");
  const users = await res.data.message;

  const paths = users.map((user: User) => ({
    params: {
      userid: user._id,
    },
  }));

  return {
    paths,
    fallback: false,
  };
};

//  Fetch the user data based on the ID from an API or database
export const getStaticProps: GetStaticProps<UserProps> = async (context) => {
  const { params } = context;
  const res = await axios.get(
    `http://localhost:4000/api/user/${params?.userid}`
  );
  const data = await res.data.message;

  return {
    props: {
      user: data,
    },
  };
};
