/* eslint-disable react-hooks/rules-of-hooks */
import { Context } from "Context/Context";
import axios from "axios";
import Loader from "components/Loader/Loader";
import Navbar from "components/Navbar/Navbar";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useContext, useState } from "react";
import { useForm } from "react-hook-form";
import styles from "../../styles/login.module.scss";

type LoginInputs = {
  emailOrUsername: string;
  password: string;
};

const index = () => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const router = useRouter();
  const {
    register,
    handleSubmit,
    formState: { errors },
    watch,
    reset,
    trigger,
  } = useForm<LoginInputs>();
  const { dispatch, user } = useContext(Context);

  /**
   * The `onSubmit` function is used to handle the login form submission, making an API request to
   * authenticate the user and store the JWT token in localStorage.
   * @param {LoginInputs} data - The `data` parameter is an object of type `LoginInputs`. It contains
   * the following properties:
   */
  const onSubmit = async (data: LoginInputs) => {
    const { emailOrUsername, password } = data;

    setLoading(true);

    try {
      dispatch({ type: "LOGIN_START" });
      const res = await axios.post(
        `${process.env.NEXT_PUBLIC_SERVER_URL}/api/auth/login`,
        {
          emailOrUsername: emailOrUsername.toLocaleLowerCase(),
          password: password,
        }
      );

      const { message, jwtToken } = res.data;
      // console.log(message);

      // Store the JWT token in localStorage
      localStorage.setItem("jwtToken", jwtToken);

      // if login is successful return the user and save the session
      dispatch({ type: "LOGIN_SUCCESS", payload: message });

      router.push(`/user/${res.data?.message.username}`);
      setError(null);
      setLoading(false);
    } catch (error: any) {
      // some code that may throw error
      setError(error.response.data?.error);
      dispatch({ type: "LOGIN_FAILURE", payload: error.response.data.error });
      setLoading(false);
    }

    setLoading(false);
  };

  if (loading) {
    return <Loader />;
  }
  return (
    <div className={styles.login_page}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by sociatek" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <div className={styles.login_page_main}>
        <div className={styles.login_page_form}>
          <h3>Login Here</h3>
          <form onSubmit={handleSubmit(onSubmit)}>
            <input
              {...register("emailOrUsername", {
                required: "This field is required!",
              })}
              placeholder="Email Or Username"
              onBlur={() => {
                trigger("emailOrUsername");
              }}
              className={styles.exact_form_inp}
              style={{ textTransform: "lowercase" }}
            />
            {/* error message */}
            <span className={styles.form_err}>
              {errors.emailOrUsername?.message}
            </span>

            <input
              type="password"
              {...register("password", {
                required: "Password is required!",
              })}
              placeholder="Password"
              onBlur={() => {
                trigger("password");
              }}
              className={styles.exact_form_inp}
            />
            <span className={styles.form_err}>{errors.password?.message}</span>

            {error && <span className={styles.form_errr}>{error}</span>}
            <input
              type="submit"
              value={loading ? "Loading..." : "Log In"}
              className={styles.submit_btn}
              style={{ cursor: loading ? "not-allowed" : "pointer" }}
            />
          </form>

          <p style={{ marginTop: "15px" }}>
            <Link href="/registration" style={{ color: "black" }}>
              {" "}
              Don&apos;t have an account? Register here..
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
};

export default index;
