/* eslint-disable react-hooks/rules-of-hooks */
import Navbar from "components/Navbar/Navbar";
import RegForm from "components/RegForm/RegForm";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import styles from "../../styles/registration.module.scss";

const index = () => {
  const Router = useRouter();
  const [page, setPage] = useState(0);
  const [email, setEmail] = useState("");
  const [pass, setPass] = useState("");
  const [conPass, setConPass] = useState("");

  const [fullname, setFullname] = useState("");
  const [userName, setUserName] = useState("");
  const [bio, setBio] = useState("");

  const [phone, setPhone] = useState("");
  const [facebookUrl, setFacebookUrl] = useState("");
  const [twitterUrl, setTwitterUrl] = useState("");

  // console.log(watch("example"));

  const eChng = (e: any) => {
    setEmail(e.target.value);
  };
  const pChng = (e) => {
    setPass(e.target.value);
  };
  const cChng = (e) => {
    setConPass(e.target.value);
  };

  const fChng = (e) => {
    setFullname(e.target.value);
  };
  const lChng = (e) => {
    setBio(e.target.value);
  };
  const uChng = (e) => {
    setUserName(e.target.value);
  };
  const phnChng = (e) => {
    setPhone(e.target.value);
  };
  const facebookUrlChng = (e) => {
    setFacebookUrl(e.target.value);
  };
  const twitterUrlChng = (e) => {
    setTwitterUrl(e.target.value);
  };

  // const handleSubmit = async (e) => {
  //   e.preventDefault();
  //   try {
  //     setLoading(true);

  //     if (photo) {
  //       const data = new FormData();
  //       data.append("file", photo);
  //       data.append("upload_preset", "upload");

  //       const uploadRes = await axios.post(
  //         "https://api.cloudinary.com/v1_1/drbvugloj/image/upload",
  //         data
  //       );

  //       const { url } = uploadRes.data;
  //       try {
  //         await axios.post(
  //           "https://rooms-backend.onrender.com/api/user/signup",
  //           {
  //             email,
  //             password: pass,
  //             fullname,
  //             bio,
  //             username: userName,
  //             image: url,
  //             phone,
  //             fblink: facebookUrl,
  //             twlink: twitterUrl,
  //           }
  //         );

  //         Router.push("/login");
  //         setLoading(false);
  //       } catch (err) {
  //         setError(true);
  //         console.log("signup error", err);
  //         setLoading(false);
  //       }
  //     } else {
  //       try {
  //         await axios.post(
  //           "https://rooms-backend.onrender.com/api/user/signup",
  //           {
  //             email,
  //             password: pass,
  //             fullname,
  //             bio,
  //             username: userName,
  //             phone,
  //             fblink: facebookUrl,
  //             twlink: twitterUrl,
  //           }
  //         );

  //         Router.push("/login");
  //         setLoading(false);
  //       } catch (err) {
  //         setError(true);
  //         console.log("signup error", err);
  //         setLoading(false);
  //       }
  //     }
  //   } catch (errr) {
  //     console.log("image error", errr);
  //     setError(true);
  //     setLoading(false);
  //   }
  // };

  return (
    <div className={styles.registration_page}>
      <Head>
        <title>Registration</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.registration_page_main}>
        <div className={styles.registration_page_form}>
          <div className={styles.registration_progress}>
            <div
              className={styles.registration_progress_widht}
              style={{
                width: page === 0 ? "33.3%" : page === 1 ? "66.6%" : "100%",
              }}
            >
              <p className={styles.registration_progress_status}>
                {page === 0 ? "33%" : page === 1 ? "66%" : "100%"}
              </p>
            </div>
          </div>

          <RegForm />
        </div>
      </div>
    </div>
  );
};

export default index;
