/* eslint-disable react-hooks/rules-of-hooks */
import Navbar from "components/Navbar/Navbar";
import RegForm from "components/RegForm/RegForm";
import Head from "next/head";
import { useState } from "react";
import styles from "../../styles/registration.module.scss";

const index = () => {
  const [page, setPage] = useState(0);
  const [loading, setLoading] = useState(false);

  if (loading) {
    return (
      <>
        <Navbar />
        <span className={styles.loader}></span>
      </>
    );
  }

  return (
    <div className={styles.registration_page}>
      <Head>
        <title>Registration</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.registration_page_main}>
        <div className={styles.registration_page_form}>
          <div className={styles.registration_progress}>
            <div
              className={styles.registration_progress_widht}
              style={{
                width: page === 0 ? "33.3%" : page === 1 ? "66.6%" : "100%",
              }}
            >
              <p className={styles.registration_progress_status}>
                {page === 0 ? "33%" : page === 1 ? "66%" : "100%"}
              </p>
            </div>
          </div>

          <RegForm
            page={page}
            setPage={setPage}
            loading={loading}
            setLoading={setLoading}
          />
        </div>
      </div>
    </div>
  );
};

export default index;
