import styles from "@/styles/Home.module.css";
import { Inter } from "@next/font/google";
import Homepage from "components/Homepage/Homepage";
import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { Postt } from "types.global";
import Navbar from "../../components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

interface PostProps {
  posts: Postt[];
}

export const revalidate = 30;

const Home: NextPage<PostProps> = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Sociatek</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />

        {/* main section of this application */}
        <Homepage posts={posts} />
      </main>
    </>
  );
};

// SSR - get called on every request
export const getServerSideProps: GetServerSideProps<PostProps> = async () => {
  const res = await fetch("https://weblog-backend.onrender.com/api/posts");
  const data = await res.json();

  return {
    props: {
      posts: data.message,
    },
  };
};

export default Home;
