import styles from "@/styles/Home.module.css";
import { Inter } from "@next/font/google";
import Homepage from "components/Homepage/Homepage";
import { GetServerSideProps } from "next";
import Head from "next/head";
import Navbar from "../../components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

interface PostProps {
  posts: {
    _id: string;
    categories: string[];
    username: string;
    title: string;
    desc: string;
    photo: string;
    createdAt: Date;
    updatedAt: Date;
  }[];
}

export default function Home({ posts }: PostProps) {
  return (
    <>
      <Head>
        <title>Weblog-2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />

        {/* main section of this application */}
        <Homepage posts={posts} />
      </main>
    </>
  );
}

// SSR - get called on every request
export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch("https://weblog-backend.onrender.com/api/posts");
  const data = await res.json();

  return {
    props: {
      posts: data.message,
    },
  };
};
