/* eslint-disable react-hooks/rules-of-hooks */
import Navbar from "components/Navbar/Navbar";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { User } from "types.global";
import styles from "../../styles/profile.module.scss";

const index = () => {
  const [user, setUser] = useState<null | User>(null);
  const router = useRouter();

  useEffect(() => {
    const userData = localStorage.getItem("user");

    if (typeof window !== "undefined" && userData) {
      setUser(JSON.parse(userData));
    }
  }, []);

  return (
    <div className={styles.singlePost}>
      <Head>
        <title>{user?.fullname}</title>
        <meta name="description" content="Generated by sociatek" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <div className={styles.singlePost_main}>
        <h1 style={{ marginTop: "100px" }}>user Profile</h1>
      </div>
    </div>
  );
};

export default index;
